import re

input = "FEFFFFFEFEFFFFFEFEFFFFFEFFFFFEFEFEFFFFFEFEFEFEFFFEFFFFFEFEFFFFFFFEFFFFFFFFFEFFFFFEFFFFFFFEFEFFFEFEFFFFFEFEFFFEFFFEFFFFFEFFFFFEFFFEFFFFFEFEFFFEFFFEFFFFFEFFFFFEFFFEFFFFFEFEFEFFFEFEFFFFFEFEFFFEFFFEFFFFFFFEFEFFFEFEFFFEFFFFFFFFFFFEFFFFFEFFFEFFFFFEFFFFFEFFFEFEFFFEFFFFFEFEFFFEFEFEFFFFFFFEFEFFFFFEFFFEFFFFFFFFFFFEFFFFFFFEFEFEFEFEFFFFFFFEFEFFFEFEFFFFFEFFFFFFFFFEFFFFFFFEFFFEFEFEFFFFFEFEFFFEFFFEFFFFFEFEFEFFFFFEFFFFFFFEFFFEFEFEFFFEFFFFFFFFFFFEFFFFFFFFFEFEFFFEFFFFFEFFFFFFFFFEFFFFFFFEFFFEFFFEFFFFFFFEFEFFFEFEFFFEFFFFFFFFFFFEFFFFFEFFFEFEFEFEFFFFFEFEFFFEFFFEFFFFFEFEFEFEFFFEFFFFFEFEFFFEFEFEFFFFFEFEFFFEFFFEFFFFFFFCFCFDF0F0F1DFDFDECCCDCDBAB9B8A7A5A593939083817E7674736E6C6A6D6B686866675857574E4E4E5754567F7D7EBCBCBFF4F4F5"

bytes_string = re.findall("..", input)
bytes_string= map(lambda x : str(bin(int(x, 16)))[-1:], bytes_string)
final = []
i = 0
while i < len(bytes_string) - 8:
	final.append(chr(int("".join(bytes_string[i:i+8]),2)))
	i += 8

print "".join(final)
